# frozen_string_literal: true

module Engine
  module Game
    module G1887
      module Entities
        COMPANIES = [
          {
            name: 'BAGS Concession',
            sym: 'BAGSC',
            value: 200,
            revenue: 60,
            desc: "Gives its buyer the 20% president's certificate of BAGS (RR). Closes when BAGS operates.",
            abilities: [],
            color: nil,
          },
          {
            name: 'BAWR Concession',
            sym: 'BAWRC',
            value: 200,
            revenue: 40,
            desc: "Gives its buyer the 20% president's certificate of BAWR (RR). Closes when BAWR operates.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Baring Charter',
            sym: 'BARC',
            value: 160,
            revenue: 0,
            desc: "Gives its buyer the 40% president's certificate of Baring Brothers (FH), which floats at once with the winning bid in its treasury and a par of at most half the bid. It holds a 20% seed in a Construction Company (CC), and closes at the start of the first Stock Round.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Hambro Charter',
            sym: 'HAMC',
            value: 160,
            revenue: 0,
            desc: "Gives its buyer the 40% president's certificate of C.J. Hambro & Co. (FH), which floats at once with the winning bid in its treasury and a par of at most half the bid. It holds a 20% seed in a Construction Company (CC), and closes at the start of the first Stock Round.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Murrieta Charter',
            sym: 'MURC',
            value: 160,
            revenue: 0,
            desc: "Gives its buyer the 40% president's certificate of E. Murrieta & Co. (FH), which floats at once with the winning bid in its treasury and a par of at most half the bid. It holds a 20% seed in a Construction Company (CC), and closes at the start of the first Stock Round.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Baring & Robertson Credit',
            sym: 'BRC',
            value: 60,
            revenue: 15,
            desc: 'Its buyer at the Initial Auction receives a 10% BAGS (RR) share. Once per game, in a Stock Round turn, its owner may move the Confidence Track back one space; it closes at phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Petro & Ladd Construction Contract',
            sym: 'PLC',
            value: 75,
            revenue: 15,
            desc: 'Its buyer at the Initial Auction receives a 10% BAGS (RR) share, and it closes at phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Robert Stephenson & Co. Locomotive Order',
            sym: 'RSL',
            value: 90,
            revenue: 15,
            desc: 'Its buyer at the Initial Auction receives a 10% BAGS (RR) share; it pays its owner 10% of the price of the first train bought from the bank in each Operating Round set, and closes at phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Henderson Transfer',
            sym: 'HT',
            value: 70,
            revenue: 15,
            desc: 'Its owner may exchange it in a Stock Round for a 10% BAWR (RR) share. If still held at phase 5, it is exchanged then.',
            abilities: [],
            color: nil,
          },
          {
            name: 'La Porteña Works',
            sym: 'LPW',
            value: 85,
            revenue: 15,
            desc: 'Its owner may exchange it in a Stock Round for a 10% BAWR (RR) share. If still held at phase 5, it is exchanged then.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Anderson Paz Purchase Agreement',
            sym: 'APPA',
            value: 55,
            revenue: 10,
            desc: 'Its owner may exchange it in a Stock Round for a 10% BAWR (RR) share. If still held at phase 5, it is exchanged then.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Kilometric Guarantee',
            sym: 'KG',
            value: 35,
            revenue: 0,
            desc: 'May be bought by a Railroad for $18 to $70, from phase 3. The owning Railroad receives $15 per station token each Operating Round ($7 from phase 5), pays the bank $15 per token at phase 6, then it closes.',
            abilities: [],
            color: nil,
          },
          {
            name: 'La Boca Docks Lease',
            sym: 'LBDL',
            value: 70,
            revenue: 15,
            desc: "May be bought by a Railroad for $35 to $140, from phase 3. Its owner's first tile on Buenos Aires (F16) or E17 skips the terrain cost, once, and it closes at phase 5.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Paraná Ferry Company',
            sym: 'PFC',
            value: 60,
            revenue: 15,
            desc: 'May be bought by a Railroad for $30 to $120, from phase 3. Only its owning Railroad may run over F24 and G21 (the way to Atlantic Export), and it pays no income from phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Lombard Street',
            sym: 'LS',
            value: 135,
            revenue: 0,
            desc: 'Comes with one BAWR (RR) share and one more Railroad share. Does not close. Its owner may buy one share per Stock Round for Lombard Street, or start a company, paying from its treasury and then his own cash. Each purchase moves the Confidence Track forward one space, and at space 7 the game ends.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Estancia Land Grant',
            sym: 'ELG',
            value: 45,
            revenue: 5,
            min_players: 4,
            desc: '4 players only. May be bought by a Railroad for $23 to $90, from phase 3. No Railroad may lay track on hex J10 until it is bought or closes, and at phase 5 it closes and pays its owner $50.',
            abilities: [{ type: 'blocks_hexes', hexes: ['J10'] }],
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'BAGS',
            name: 'Buenos Aires Great Southern (RR)',
            logo: '1887/BAGS',
            float_percent: 20,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F16',
            color: '#e8734a',
          },
          {
            sym: 'BAWR',
            name: 'Buenos Aires Western (RR)',
            logo: '1887/BAWR',
            float_percent: 20,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F12',
            color: '#7030a0',
          },
          {
            sym: 'SFW',
            name: 'Santa Fe Western (RR)',
            logo: '1887/SFW',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80, 80],
            coordinates: 'E9',
            color: '#f0b400',
            text_color: 'black',
          },
          {
            sym: 'BBNW',
            name: 'Bahia Blanca & North Western (RR)',
            logo: '1887/BBNW',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'L8',
            color: '#4472c4',
          },
          {
            sym: 'ANW',
            name: 'Argentine North Western (RR)',
            logo: '1887/ANW',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80, 80],
            coordinates: 'B10',
            color: '#8a8a8a',
          },
          {
            sym: 'BAP',
            name: 'Buenos Aires & Pacific (RR)',
            logo: '1887/BAP',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'G7',
            color: '#c2358a',
          },
          {
            sym: 'ER',
            name: 'Entre Rios Railway (RR)',
            logo: '1887/ER',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F26',
            color: '#8bc34a',
            text_color: 'black',
          },
          {
            sym: 'BB',
            name: 'Baring Brothers (FH)',
            logo: '1887/BB',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#262626',
          },
          {
            sym: 'HAM',
            name: 'C.J. Hambro & Co. (FH)',
            logo: '1887/HAM',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#f4a6b8',
            text_color: 'black',
          },
          {
            sym: 'MUR',
            name: 'E. Murrieta & Co. (FH)',
            logo: '1887/MUR',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#1b5e20',
          },
          {
            sym: 'BWW',
            name: 'Brassey, Wythes & Wheelwright (CC)',
            logo: '1887/BWW',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#8c6239',
          },
          {
            sym: 'J&MC',
            name: 'John & Matthew Clark (CC)',
            logo: '1887/JMC',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#1f8a8a',
          },
          {
            sym: 'MEIG',
            name: 'John Meiggs & Co. (CC)',
            logo: '1887/MEIG',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#d6cba5',
            text_color: 'black',
          },
        ].freeze
      end
    end
  end
end
