# frozen_string_literal: true

module Engine
  module Game
    module G1887
      module Entities
        COMPANIES = [
          {
            name: 'BAGS Concession',
            sym: 'BAGSC',
            value: 200,
            revenue: 60,
            desc: "Gives its buyer the 20% president's certificate of BAGS (RR) when it is bought; the buyer becomes BAGS's president. Closes at the start of BAGS's first operating turn, after paying its income that round.",
            abilities: [],
            color: nil,
          },
          {
            name: 'BAWR Concession',
            sym: 'BAWRC',
            value: 200,
            revenue: 40,
            desc: "Gives its buyer the 20% president's certificate of BAWR (RR) when it is bought; the buyer becomes BAWR's president. Closes at the start of BAWR's first operating turn, after paying its income that round.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Baring Charter',
            sym: 'BARC',
            value: 160,
            revenue: 0,
            desc: "Gives its buyer the 40% president's certificate of Baring Brothers (FH). Baring Brothers (FH) floats at once: the winning bid is paid into its treasury, and its par is the highest par not above half the winning bid. Baring Brothers (FH) keeps its 20% seed certificate in a Construction Company; the buyer gets none of it. Closes at the start of the first Stock Round. Until then it counts toward no limit and no score.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Hambro Charter',
            sym: 'HAMC',
            value: 160,
            revenue: 0,
            desc: "Gives its buyer the 40% president's certificate of C.J. Hambro & Co. (FH). C.J. Hambro & Co. (FH) floats at once: the winning bid is paid into its treasury, and its par is the highest par not above half the winning bid. C.J. Hambro & Co. (FH) keeps its 20% seed certificate in a Construction Company; the buyer gets none of it. Closes at the start of the first Stock Round. Until then it counts toward no limit and no score.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Murrieta Charter',
            sym: 'MURC',
            value: 160,
            revenue: 0,
            desc: "Gives its buyer the 40% president's certificate of E. Murrieta & Co. (FH). E. Murrieta & Co. (FH) floats at once: the winning bid is paid into its treasury, and its par is the highest par not above half the winning bid. E. Murrieta & Co. (FH) keeps its 20% seed certificate in a Construction Company; the buyer gets none of it. Closes at the start of the first Stock Round. Until then it counts toward no limit and no score.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Baring & Robertson Credit',
            sym: 'BRC',
            value: 60,
            revenue: 15,
            desc: 'Its buyer at the Initial Auction receives a free 10% BAGS (RR) share. Once per game, in a Stock Round turn, its owner may move the Confidence Track back one space (not from space 1, not from space 7). A Railroad may not buy it. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Petro & Ladd Construction Contract',
            sym: 'PLC',
            value: 75,
            revenue: 15,
            desc: 'May be bought by a Railroad for $38 to $150 from the player at the top of its chain, from phase 3. Its buyer at the Initial Auction receives a free 10% BAGS (RR) share. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Robert Stephenson & Co. Locomotive Order',
            sym: 'RSL',
            value: 90,
            revenue: 15,
            desc: 'May be bought by a Railroad for $45 to $180 from the player at the top of its chain, from phase 3. Its buyer at the Initial Auction receives a free 10% BAGS (RR) share. Pays its owner (a player or a Railroad) 10% of the price of the first train bought from the bank in each Operating Round set: once per Operating Round set, not once per Operating Round. Closes at the start of phase 5 (so it pays nothing on the 5-train that closes it).',
            abilities: [],
            color: nil,
          },
          {
            name: 'Henderson Transfer',
            sym: 'HT',
            value: 70,
            revenue: 15,
            desc: "In a Stock Round its owner may exchange it for a free 10% BAWR (RR) share from BAWR's held-back shares; this is not the turn's buy, and any number of exchanges may be made in a turn. Closes at the start of phase 5; if a player still holds it then, it is exchanged at that moment.",
            abilities: [],
            color: nil,
          },
          {
            name: 'La Porteña Works',
            sym: 'LPW',
            value: 85,
            revenue: 15,
            desc: "In a Stock Round its owner may exchange it for a free 10% BAWR (RR) share from BAWR's held-back shares; this is not the turn's buy, and any number of exchanges may be made in a turn. Closes at the start of phase 5; if a player still holds it then, it is exchanged at that moment.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Anderson Paz Purchase Agreement',
            sym: 'APPA',
            value: 55,
            revenue: 10,
            desc: "In a Stock Round its owner may exchange it for a free 10% BAWR (RR) share from BAWR's held-back shares; this is not the turn's buy, and any number of exchanges may be made in a turn. Closes at the start of phase 5; if a player still holds it then, it is exchanged at that moment.",
            abilities: [],
            color: nil,
          },
          {
            name: 'Kilometric Guarantee',
            sym: 'KG',
            value: 35,
            revenue: 0,
            desc: 'May be bought by a Railroad for $18 to $70 from the player at the top of its chain, from phase 3. Does nothing while a player owns it. A Railroad that owns it receives $15 for each station token it has placed, home station included, at the start of each Operating Round ($7 from phase 5). At the start of phase 6 that Railroad pays the bank $15 for each station token; what it cannot pay, its president (the player at the top of its chain) pays from personal cash, selling shares if he must; if he still cannot, he is bankrupt. Then it closes.',
            abilities: [],
            color: nil,
          },
          {
            name: 'La Boca Docks Lease',
            sym: 'LBDL',
            value: 70,
            revenue: 15,
            desc: 'May be bought by a Railroad for $35 to $140 from the player at the top of its chain, from phase 3. The first time its owning Railroad lays or upgrades a tile on Buenos Aires (F16) or on E17, where a terrain cost is printed, that terrain cost is not charged (once only). Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Paraná Ferry Company',
            sym: 'PFC',
            value: 60,
            revenue: 15,
            desc: 'May be bought by a Railroad for $30 to $120 from the player at the top of its chain, from phase 3. Only a Railroad that owns it may run a route over F24 or G21 (the way to the Atlantic Export). Stays open when phase 5 begins, but pays no income from then on.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Lombard Street',
            sym: 'LS',
            value: 135,
            revenue: 0,
            desc: 'Closes when it is bought; its buyer owns Lombard Street, which holds cash and shares and acts only through its owner. Once per Stock Round its owner may have Lombard Street buy one certificate, or start a company, instead of his own buy; Lombard Street pays what its treasury allows and its owner pays the rest. Each such action moves the Confidence Track forward one space. Lombard Street may start a Construction Company that has never been started, a retired Construction Company or Railroad, and, from the first 4-train, a Railroad that has never been started.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Estancia Land Grant',
            sym: 'ELG',
            value: 45,
            revenue: 5,
            min_players: 4,
            desc: '4 players only. May be bought by a Railroad for $23 to $90 from the player at the top of its chain, from phase 3. No Railroad may lay track in hex J10 until a Railroad has bought it or it closes. Closes at the start of phase 5; its owner, a player or a Railroad, then receives $50 from the bank.',
            abilities: [{ type: 'blocks_hexes', hexes: ['J10'] }],
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'BAGS',
            name: 'Buenos Aires Great Southern (RR)',
            logo: '1887/BAGS',
            float_percent: 20,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F16',
            color: '#e8734a',
          },
          {
            sym: 'BAWR',
            name: 'Buenos Aires Western (RR)',
            logo: '1887/BAWR',
            float_percent: 20,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F12',
            color: '#7030a0',
          },
          {
            sym: 'SFW',
            name: 'Santa Fe Western (RR)',
            logo: '1887/SFW',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80, 80],
            coordinates: 'E9',
            color: '#f0b400',
            text_color: 'black',
          },
          {
            sym: 'BBNW',
            name: 'Bahia Blanca & North Western (RR)',
            logo: '1887/BBNW',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'L8',
            color: '#4472c4',
          },
          {
            sym: 'ANW',
            name: 'Argentine North Western (RR)',
            logo: '1887/ANW',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80, 80],
            coordinates: 'B10',
            color: '#8a8a8a',
          },
          {
            sym: 'BAP',
            name: 'Buenos Aires & Pacific (RR)',
            logo: '1887/BAP',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'G7',
            color: '#c2358a',
          },
          {
            sym: 'ER',
            name: 'Entre Rios Railway (RR)',
            logo: '1887/ER',
            float_percent: 20,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F26',
            color: '#8bc34a',
            text_color: 'black',
          },
          {
            sym: 'BB',
            name: 'Baring Brothers (FH)',
            logo: '1887/BB',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#262626',
          },
          {
            sym: 'HAM',
            name: 'C.J. Hambro & Co. (FH)',
            logo: '1887/HAM',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#f4a6b8',
            text_color: 'black',
          },
          {
            sym: 'MUR',
            name: 'E. Murrieta & Co. (FH)',
            logo: '1887/MUR',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#1b5e20',
          },
          {
            sym: 'BWW',
            name: 'Brassey, Wythes & Wheelwright (CC)',
            logo: '1887/BWW',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#8c6239',
          },
          {
            sym: 'J&MC',
            name: 'John & Matthew Clark (CC)',
            logo: '1887/JMC',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#1f8a8a',
          },
          {
            sym: 'MEIG',
            name: 'John Meiggs & Co. (CC)',
            logo: '1887/MEIG',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#d6cba5',
            text_color: 'black',
          },
        ].freeze
      end
    end
  end
end
