# frozen_string_literal: true

module Engine
  module Game
    module G1887
      module Entities
        COMPANIES = [
          {
            name: 'BAGS Concession',
            sym: 'BAGSC',
            value: 200,
            revenue: 60,
            desc: '20% BAGS president\'s certificate. Closes when BAGS operates.',
            abilities: [],
            color: nil,
          },
          {
            name: 'BAWR Concession',
            sym: 'BAWRC',
            value: 200,
            revenue: 40,
            desc: '20% BAWR president\'s certificate. Closes when BAWR operates.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Baring Charter',
            sym: 'BARC',
            value: 160,
            revenue: 0,
            desc: '40% president\'s certificate for Baring Brothers. Purchasing this floats Baring Brothers; the winning bid is paid into its treasury, and the buyer sets its par value. Baring Brothers itself holds one 20% Construction Company seed certificate, per Setup. They belong to the Finance House, not to the buyer. Closes upon receipt of charter.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Hambro Charter',
            sym: 'HAMC',
            value: 160,
            revenue: 0,
            desc: '40% president\'s certificate for C.J. Hambro & Co. Purchasing this floats C.J. Hambro & Co.; the winning bid is paid into its treasury, and the buyer sets its par value. C.J. Hambro & Co. itself holds one 20% Construction Company seed certificate, per Setup. They belong to the Finance House, not to the buyer. Closes upon receipt of charter.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Murrieta Charter',
            sym: 'MURC',
            value: 160,
            revenue: 0,
            desc: '40% president\'s certificate for E. Murrieta & Co. Purchasing this floats E. Murrieta & Co.; the winning bid is paid into its treasury, and the buyer sets its par value. E. Murrieta & Co. itself holds one 20% Construction Company seed certificate, per Setup. They belong to the Finance House, not to the buyer. Closes upon receipt of charter.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Baring & Robertson Credit',
            sym: 'BRC',
            value: 60,
            revenue: 15,
            desc: 'Comes with a 10% BAGS share. Once per game, owner may pull the Confidence Track back one space. Not corporate-purchasable -- this power belongs to the owner, not a Railway. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Petro & Ladd Construction Contract',
            sym: 'PLC',
            value: 75,
            revenue: 15,
            desc: 'Comes with a 10% BAGS share. Corporate-purchasable by a Railway. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Robert Stephenson & Co. Locomotive Order',
            sym: 'RSL',
            value: 90,
            revenue: 15,
            desc: 'Comes with a 10% BAGS share. Pays its owner 10% of the purchase price of the first train bought from the bank in each Operating Round Set -- once per set, no matter how many trains or train types are bought during that set, not once per individual OR. Corporate-purchasable by a Railway. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Henderson Transfer',
            sym: 'HT',
            value: 70,
            revenue: 15,
            desc: 'May exchange, during a Stock Round, for a 10% share of the BAWR. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'La Porteña Works',
            sym: 'LPW',
            value: 85,
            revenue: 15,
            desc: 'Named for Argentina\'s first steam locomotive, which ran on BAWR\'s own predecessor line starting in 1857. May exchange, during a Stock Round, for a 10% share of the BAWR. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Anderson Paz Purchase Agreement',
            sym: 'APPA',
            value: 55,
            revenue: 10,
            desc: 'May exchange, during a Stock Round, for a 10% share of the BAWR. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Kilometric Guarantee',
            sym: 'KG',
            value: 35,
            revenue: 0,
            desc: 'Corporate-purchasable by a Railway. Once owned by a Railway, pays a subsidy of $15 per station token that Railway has built (including its home station) each Operating Round. In phase 5, the subsidy drops to a flat $7 per token per OR. At the start of phase 6, instead of continuing to pay a subsidy, the owning Railway must pay the bank a one-time clawback of $15 per station token it has built. The private then closes.',
            abilities: [],
            color: nil,
          },
          {
            name: 'La Boca Docks Lease',
            sym: 'LBDL',
            value: 70,
            revenue: 15,
            desc: 'Corporate-purchasable by a Railway. Ignores terrain cost the first time this Railway builds track into Buenos Aires - the historic La Boca docks sat on reclaimed swampland at the mouth of the Riachuelo, which is exactly the swamp terrain cost this waives. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Parana Ferry Company',
            sym: 'PFC',
            value: 60,
            revenue: 15,
            desc: 'Corporate-purchasable by a Railway: permanently substitutes for a normal ferry marker on that Railway. Hexes F24 and G21 (marked with the ferry icon on the map) cannot be used by any Railway that doesn\'t own this private. This is the only way to reach the Atlantic Export off-board. Closes at the start of phase 5.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Lombard Street',
            sym: 'LS',
            value: 135,
            revenue: 0,
            desc: 'Closed upon receipt of Lombard charter.',
            abilities: [],
            color: nil,
          },
          {
            name: 'Estancia Land Grant',
            sym: 'ELG',
            value: 45,
            revenue: 5,
            min_players: 4,
            desc: '4-PLAYER ONLY. Corporate-purchasable by a Railway. A Railway cannot build track into hex J10 (a plain countryside hex just outside Tandil, in the historic ranching heartland of Buenos Aires province) until this private is either bought into a Railway\'s treasury or closes. Closes at the start of phase 5. Pays its owner a flat $50 bonus when it closes, instead of a special power.',
            abilities: [],
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            sym: 'BAGS',
            name: 'Buenos Aires Great Southern',
            logo: '1887/BAGS',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F16',
            color: '#e8734a',
          },
          {
            sym: 'BAWR',
            name: 'Buenos Aires Western',
            logo: '1887/BAWR',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F12',
            color: '#7030a0',
          },
          {
            sym: 'SFW',
            name: 'Santa Fe Western',
            logo: '1887/SFW',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80, 80],
            coordinates: 'E9',
            color: '#f0b400',
            text_color: 'black',
          },
          {
            sym: 'BBNW',
            name: 'Bahia Blanca & North Western',
            logo: '1887/BBNW',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'L8',
            color: '#4472c4',
          },
          {
            sym: 'ANW',
            name: 'Argentine North Western',
            logo: '1887/ANW',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80, 80],
            coordinates: 'B10',
            color: '#8a8a8a',
          },
          {
            sym: 'BAP',
            name: 'Buenos Aires & Pacific',
            logo: '1887/BAP',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'G7',
            color: '#c2358a',
          },
          {
            sym: 'ER',
            name: 'Entre Rios Railway',
            logo: '1887/ER',
            float_percent: 20,
            corporation_can_ipo: true,
            tokens: [0, 40, 80],
            coordinates: 'F26',
            color: '#8bc34a',
            text_color: 'black',
          },
          {
            sym: 'BB',
            name: 'Baring Brothers',
            logo: '1887/BB',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#262626',
          },
          {
            sym: 'HAM',
            name: 'C.J. Hambro & Co.',
            logo: '1887/HAM',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#f4a6b8',
            text_color: 'black',
          },
          {
            sym: 'MUR',
            name: 'E. Murrieta & Co.',
            logo: '1887/MUR',
            float_percent: 40,
            capitalization: :incremental,
            always_market_price: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#1b5e20',
          },
          {
            sym: 'BWW',
            name: 'Brassey, Wythes & Wheelwright',
            logo: '1887/BWW',
            float_percent: 40,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#8c6239',
          },
          {
            sym: 'J&MC',
            name: 'John & Matthew Clark',
            logo: '1887/JMC',
            float_percent: 40,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#1f8a8a',
          },
          {
            sym: 'MEIG',
            name: 'John Meiggs & Co.',
            logo: '1887/MEIG',
            float_percent: 40,
            corporation_can_ipo: true,
            shares: [40, 20, 20, 20],
            tokens: [],
            color: '#d6cba5',
            text_color: 'black',
          },
        ].freeze
      end
    end
  end
end
